export default {
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
  GET_USER_RESERVATIONS: "GET_USER_RESERVATIONS",
  GET_BUILDINGS: "GET_BUILDINGS",
  SET_RESERVATION_BUILDING: "SET_RESERVATION_BUILDING",
  SET_RESERVATION_FLOOR: "SET_RESERVATION_FLOOR",
  SET_RESERVATION_TODAY: "SET_RESERVATION_TODAY",
  GET_FLOOR_DATA: "GET_FLOOR_DATA",
  QUICK_RESERVATION_REQUEST: "QUICK_RESERVATION_REQUEST",
  CLEAR_RESERVATION_REQUEST: "CLEAR_RESERVATION_REQUEST",
  DELETE_RESERVATION: "DELETE_RESERVATION",
  SET_NEW_RESERVATION: "SET_NEW_RESERVATION",
};
